sudo: required
services:
  - docker

before_install:
  - docker build -t pranav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pranav/react-test npm test -- --coverage

after_success:
  - docker build -t pranav0073/multi-client ./client
  - docker build -t pranav0073/multi-nginx ./nginx
  - docker build -t pranav0073/server ./server
  - docker build -t pranav0073/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pranav0073/multi-client
  - docker push pranav0073/multi-nginx
  - docker push pranav0073/server
  - docker push pranav0073/worker